<?php

use CidiLabs\PhpAlly\Rule\VideosHaveAutoGeneratedCaptions;

class VideosHaveAutoGeneratedCaptionsTest extends PhpAllyTestCase {

    public function testCheckTwoIssues()
    {
        $html = '<embed type="video/webm" src="https://www.youtube.com/watch?v=liJVSwOiiwg" width="400" height="300">';
        $dom = new \DOMDocument('1.0', 'utf-8');
        $dom->loadHTML($html);
        $options = [
            'vimeoApiKey' => 'bef37736cfb26b6dc52986d8f531d0ad',
            'youtubeApiKey' => 'AIzaSyB5bTf8rbYwiM73k1rj8dDnwEalwTqdz_c'
        ];
        $rule = new VideosHaveAutoGeneratedCaptions($dom, $options);

        $this->assertEquals(1, $rule->check(), 'Youtube Test should return 1 failed test to indicate auto-generated captions');
    }

    public function testCaptionsMissingHasCaptions()
    {
        $html = '<embed type="video/webm" src="https://www.youtube.com/watch?v=qfJthDvcZ08" width="400" height="300">';
        $dom = new \DOMDocument('1.0', 'utf-8');
        $dom->loadHTML($html);
        $options = [
            'vimeoApiKey' => 'bef37736cfb26b6dc52986d8f531d0ad',
            'youtubeApiKey' => 'AIzaSyB5bTf8rbYwiM73k1rj8dDnwEalwTqdz_c'
        ];
        $rule = new VideosHaveAutoGeneratedCaptions($dom, $options);

        $this->assertEquals(0, $rule->check(), 'Youtube Test should return 0 failed tests to indicate no missing captions');
    }
}