<?php

namespace CidiLabs\PhpAlly\Rule;

use CidiLabs\PhpAlly\Youtube;

/**
 *	Links to YouTube videos must have a caption
 */
class VideosHaveAutoGeneratedCaptions extends BaseRule
{
	const VIDEO_HAS_CUSTOM_CAPTIONS = 2;

	public function id()
	{
		return self::class;
	}

	public function check()
	{
		$service = null;
		$search_youtube = '/(youtube|youtu.be)/';

		foreach ($this->getAllElements(array('a', 'embed', 'iframe')) as $video) {
			$attr = ($video->tagName == 'a') ? 'href' : 'src';
			if ($video->hasAttribute($attr)) {
				$attr_val = $video->getAttribute($attr);
				if (preg_match($search_youtube, $attr_val)) {
					$service = new Youtube(new \GuzzleHttp\Client(['http_errors' => false]), $this->lang);
				}

				if (isset($service)) {
					$captionState = $service->captionsAutoGenerated($attr_val);
					if ($captionState != self::VIDEO_HAS_CUSTOM_CAPTIONS) {
						$this->setIssue($video);
					}
				}
			}
		}

		return count($this->issues);
	}
}
