<?php

namespace CidiLabs\PhpAlly\Video;

use CidiLabs\PhpAlly\Youtube;

/**
 *	Links to YouTube videos must have a caption
 */
class VideosHaveAutoGeneratedCaptions
{
	const VIDEO_HAS_CUSTOM_CAPTIONS = 2;

	public function id()
	{
		return self::class;
	}

	public function check()
	{
		foreach ($this->getAllElements(array('a', 'embed', 'iframe')) as $video) {
			$attr = ($video->tagName == 'a') ? 'href' : 'src';
			if ($video->hasAttribute($attr)) {
				$attr_val = $video->getAttribute($attr);
				$captionState = $this->getCaptionState($attr_val);
				if ($captionState != self::VIDEO_HAS_CUSTOM_CAPTIONS) {
					$this->setIssue($video);
				}
			}
		}

		return count($this->issues);
	}

	public function getCaptionState($attr_val)
	{
		$service = null;
		$search_youtube = '/(youtube|youtu.be)/';

		if (preg_match($search_youtube, $attr_val)) {
			$service = new Youtube(new \GuzzleHttp\Client(['http_errors' => false]), $this->lang, $this->options['youtubeApiKey']);
		}

		if (isset($service)) {
			$captionState = $service->captionsAutoGenerated($attr_val);
			return $captionState;
		}

		return self::VIDEO_HAS_CUSTOM_CAPTIONS;
	}
}
